version: '3.8'
services:
  server:
    container_name: server
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/data/certs:/etc/nginx/certs
    depends_on:
      - api

  db:
    container_name: db
    image: asterixinfintum/data-xcv:latest
    volumes:
      - mve_mongodb_data:/data/db

  api:
    container_name: api
    restart: always
    build: ./api
    environment:
      - PORT=8001

  chatapi:
    container_name: chatapi
    restart: always
    build: ./chat
    environment:
      - PORT=8002
      
  nuxt-app:
    build: ./ui
    container_name: nuxt-app
    restart: always
    environment:
      - PORT=4000
    command: 'npm run start'

volumes:
  mve_mongodb_data:
    external: true